// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/auth/internal/model"
)

// AuthService defines business logic operations for Auth.
// Implement this interface in a separate (non-generated) file.
type AuthService interface {
	Register(ctx context.Context, req model.RegisterRequest) (model.AuthResponse, error)
	Login(ctx context.Context, req model.LoginRequest) (model.AuthResponse, error)
	Refresh(ctx context.Context, req model.RefreshRequest) (model.AuthResponse, error)
	Logout(ctx context.Context, req model.LogoutRequest) error
	Me(ctx context.Context) (model.UserResponse, error)
}
