// Code generated by apigen. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/google/uuid"

	"github.com/getnyx/influaudit/backend/internal/metrics/internal/model"
)

// MetricsRepository defines data-access operations for Metrics.
// Implement this interface in a separate (non-generated) file.
type MetricsRepository interface {
	GetInfluencerMetrics(ctx context.Context, id string, req model.MetricSeriesRequest) (model.MetricSeriesResponse, error)
	ListInfluencerPosts(ctx context.Context, id string, req model.ListPostsRequest) ([]model.PostResponse, error)
	GetInfluencerProfileSummary(ctx context.Context, id string) (model.ProfileSummaryResponse, error)
	// FollowerSeries is a facade-only read (no HTTP route): it backs the metrics
	// module's InstagramFollowerSeries method for the scoring module.
	FollowerSeries(ctx context.Context, influencerID uuid.UUID) ([]model.FollowerPoint, error)
}
