// Code generated by apigen. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/metrics/internal/model"
)

// MetricsRepository defines data-access operations for Metrics.
// Implement this interface in a separate (non-generated) file.
type MetricsRepository interface {
	GetInfluencerMetrics(ctx context.Context, id string, req model.MetricSeriesRequest) (model.MetricSeriesResponse, error)
	ListInfluencerPosts(ctx context.Context, id string, req model.ListPostsRequest) ([]model.PostResponse, error)
}
