// Code generated by apigen. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/billing/internal/model"
)

// BillingRepository defines data-access operations for Billing.
// Implement this interface in a separate (non-generated) file.
type BillingRepository interface {
	ListPlans(ctx context.Context) ([]model.PlanResponse, error)
	GetSubscription(ctx context.Context) (model.SubscriptionResponse, error)
	Subscribe(ctx context.Context, req model.SubscribeRequest) (model.SubscriptionResponse, error)
	Webhook(ctx context.Context, req model.WebhookRequest) error
}
