// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/bulkaudit/internal/model"
)

// BulkAuditService defines business logic operations for BulkAudit.
// Implement this interface in a separate (non-generated) file.
type BulkAuditService interface {
	CreateBulkAudit(ctx context.Context, req model.CreateBulkAuditRequest) (model.BulkAuditResponse, error)
	ListBulkAudits(ctx context.Context) ([]model.BulkAuditResponse, error)
	GetBulkAudit(ctx context.Context, id string) (model.BulkAuditResponse, error)
}
