// Code generated by apigen. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/oauth/internal/model"
)

// OAuthRepository defines data-access operations for OAuth.
// Implement this interface in a separate (non-generated) file.
type OAuthRepository interface {
	Authorize(ctx context.Context, provider string) (model.AuthorizeResponse, error)
	Callback(ctx context.Context, provider string) (model.ConnectionResponse, error)
	Connections(ctx context.Context) ([]model.ConnectionResponse, error)
	Disconnect(ctx context.Context, provider string) error
}
