// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/admin/internal/model"
)

// AdminService defines business logic operations for Admin.
// Implement this interface in a separate (non-generated) file.
type AdminService interface {
	FileDispute(ctx context.Context, id string, req model.FileDisputeRequest) (model.DisputeResponse, error)
	ListDisputeQueue(ctx context.Context) ([]model.DisputeResponse, error)
	ResolveDispute(ctx context.Context, id string, req model.ResolveDisputeRequest) (model.DisputeResponse, error)
	CostDashboard(ctx context.Context) (model.CostDashboardResponse, error)
	QueueMonitor(ctx context.Context) (model.QueueMonitorResponse, error)
	ExportLabels(ctx context.Context) (model.LabelExportResponse, error)
}
