// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/whitelabel/internal/model"
)

// WhitelabelService defines business logic operations for Whitelabel.
// Implement this interface in a separate (non-generated) file.
type WhitelabelService interface {
	GetWhitelabel(ctx context.Context) (model.WhitelabelResponse, error)
	UpdateWhitelabel(ctx context.Context, req model.UpdateWhitelabelRequest) (model.WhitelabelResponse, error)
}
