// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/campaign/internal/model"
)

// CampaignService defines business logic operations for Campaign.
// Implement this interface in a separate (non-generated) file.
type CampaignService interface {
	CreateCampaign(ctx context.Context, req model.CreateCampaignRequest) (model.CampaignResponse, error)
	ListCampaigns(ctx context.Context) ([]model.CampaignResponse, error)
	GetCampaign(ctx context.Context, id string) (model.CampaignResponse, error)
}
