import "server-only";
import { backendFetch } from "@/lib/api/http";

/**
 * The result-page profile summary (PRD §8): already-captured data the audit
 * gathered, surfaced for display — an audience snapshot, a verified-metrics strip,
 * and a media-kit readiness meter.
 *
 * These types are HAND-WRITTEN on purpose rather than imported from
 * `@influaudit/contracts`: the OpenAPI/TS contracts are regenerated by the
 * orchestrator later, so keeping the shape local makes this web slice
 * self-contained and reviewable on its own.
 *
 * HONESTY carries into the types. Every strip metric is optional: `undefined`
 * means "not measured", and the UI must render that as an explicit "—/not
 * measured", never as 0. A demographic dimension that was not pulled is an
 * absent map, not a zero-filled one.
 */

/** Bucket label -> audience fraction in [0,1]. */
export type Distribution = Record<string, number>;

export interface AudienceSnapshot {
  /** Age-band distribution (e.g. "18-24" -> 0.42). Absent when not pulled. */
  age?: Distribution;
  /** Gender distribution. Absent when not pulled. */
  gender?: Distribution;
  /** Country distribution (ISO-3166 alpha-2 -> fraction). Absent when not pulled. */
  country?: Distribution;
  // NOTE: no language — Meta's follower_demographics does not expose it.
}

export interface MetricsStrip {
  /** Latest follower count. Absent = not measured. */
  followers?: number;
  /** Mean per-post (likes+comments+shares)/followers, a fraction. Absent = not measured. */
  engagement_rate?: number;
  /** Median per-media reach/followers. Absent = not measured. */
  reach_ratio?: number;
  /** Median per-post saves/reach, a fraction. Absent = not measured. */
  save_rate?: number;
  /** Median per-post shares/reach, a fraction. Absent = not measured. */
  share_rate?: number;
  /** Median days between recent posts. Absent = not measured. */
  posting_cadence_days?: number;
}

export interface ReadinessField {
  field: string;
  present: boolean;
}

export interface Readiness {
  /** Share of checklist fields present, in [0,1]. A meter, never a score. */
  fraction: number;
  fields: ReadinessField[];
}

export interface ProfileSummary {
  influencer_id: string;
  audience: AudienceSnapshot;
  metrics_strip: MetricsStrip;
  readiness: Readiness;
}

/** GET /influencers/{id}/profile-summary — the result-page profile summary. */
export function getProfileSummary(
  influencerId: string,
  token: string,
): Promise<ProfileSummary> {
  return backendFetch<ProfileSummary>(
    `/influencers/${encodeURIComponent(influencerId)}/profile-summary`,
    { token },
  );
}
