// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/billing/internal/model"
)

// BillingService defines business logic operations for Billing.
// Implement this interface in a separate (non-generated) file.
type BillingService interface {
	ListPlans(ctx context.Context) ([]model.PlanResponse, error)
	GetSubscription(ctx context.Context) (model.SubscriptionResponse, error)
	Subscribe(ctx context.Context, req model.SubscribeRequest) (model.SubscriptionResponse, error)
	Webhook(ctx context.Context, req model.WebhookRequest) error
}
