// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/alerts/internal/model"
)

// AlertsService defines business logic operations for Alerts.
// Implement this interface in a separate (non-generated) file.
type AlertsService interface {
	ListAlerts(ctx context.Context) ([]model.AlertResponse, error)
	CreateAlert(ctx context.Context, req model.CreateAlertRequest) (model.AlertResponse, error)
	DeleteAlert(ctx context.Context, id string) error
}
