// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/scoring/internal/model"
)

// ScoringService defines business logic operations for Scoring.
// Implement this interface in a separate (non-generated) file.
type ScoringService interface {
	GetLatestScore(ctx context.Context, id string) (model.ScoreResponse, error)
	GetScoreHistory(ctx context.Context, id string) (model.ScoreHistoryResponse, error)
}
