// Code generated by apigen. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/influencer/internal/model"
)

// InfluencerRepository defines data-access operations for Influencer.
// Implement this interface in a separate (non-generated) file.
type InfluencerRepository interface {
	CreateInfluencer(ctx context.Context, req model.CreateInfluencerRequest) (model.InfluencerResponse, error)
	GetInfluencer(ctx context.Context, id string) (model.InfluencerResponse, error)
	ListInfluencers(ctx context.Context, req model.ListInfluencersRequest) (model.ListInfluencersResponse, error)
	UpdateInfluencer(ctx context.Context, id string, req model.UpdateInfluencerRequest) (model.InfluencerResponse, error)
	AddHandle(ctx context.Context, id string, req model.AddHandleRequest) (model.HandleResponse, error)
	DeleteHandle(ctx context.Context, id string, handleID string) error
}
