// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/audit/internal/model"
)

// AuditService defines business logic operations for Audit.
// Implement this interface in a separate (non-generated) file.
type AuditService interface {
	SubmitAudit(ctx context.Context, req model.SubmitAuditRequest) (model.AuditResponse, error)
	GetAudit(ctx context.Context, id string) (model.AuditResponse, error)
	ListAudits(ctx context.Context) ([]model.AuditResponse, error)
}
