// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/mlops/internal/model"
)

// MLOpsService defines business logic operations for MLOps.
// Implement this interface in a separate (non-generated) file.
type MLOpsService interface {
	ExportFeatureRows(ctx context.Context, req model.FeatureRowQuery) (model.FeatureRowExportResponse, error)
	RegisterModel(ctx context.Context, req model.RegisterModelRequest) (model.RegisterModelResponse, error)
	PromoteModel(ctx context.Context, version string, req model.PromoteModelRequest) (model.PromoteModelResponse, error)
	ListCanaries(ctx context.Context, req model.CanaryQuery) (model.CanaryListResponse, error)
	CreateCanary(ctx context.Context, req model.CreateCanaryRequest) (model.CanaryResponse, error)
	IngestPrediction(ctx context.Context, req model.PredictionLogRequest) (model.PredictionLogResponse, error)
}
