// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/getnyx/influaudit/backend/internal/oauth/internal/model"
)

// OAuthService defines business logic operations for OAuth.
// Implement this interface in a separate (non-generated) file.
type OAuthService interface {
	Authorize(ctx context.Context, provider string) (model.AuthorizeResponse, error)
	Callback(ctx context.Context, provider string) (model.ConnectionResponse, error)
	Connections(ctx context.Context) ([]model.ConnectionResponse, error)
	Disconnect(ctx context.Context, provider string) error
}
